language: python
python:
- '3.6'
services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database sendit;' -U postgres
- export FLASK_ENV=development
script:
- pytest tests --cov=api --cov-report term-missing
after_success:
- coveralls
